"""updated schema for rooms, room_access_logs, security_events with using server timing for times

Revision ID: a368e1c75f7e
Revises: c758bbdf6f0a
Create Date: 2026-03-13 00:33:35.778883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a368e1c75f7e'
down_revision: Union[str, Sequence[str], None] = 'c758bbdf6f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
