"""schema for rooms, room_access_logs, security_events

Revision ID: c758bbdf6f0a
Revises: 0784d8a6cdfc
Create Date: 2026-03-13 00:30:28.343004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c758bbdf6f0a'
down_revision: Union[str, Sequence[str], None] = '0784d8a6cdfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_code', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_by_ip', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    sa.UniqueConstraint('room_code', name=op.f('uq_rooms_room_code'))
    )
    op.create_index('ix_rooms_is_active', 'rooms', ['is_active'], unique=False)
    op.create_index('ix_rooms_last_activity_at', 'rooms', ['last_activity_at'], unique=False)
    op.create_index('ix_rooms_room_code', 'rooms', ['room_code'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_events'))
    )
    op.create_index('ix_security_events_created_at', 'security_events', ['created_at'], unique=False)
    op.create_index('ix_security_events_severity', 'security_events', ['severity'], unique=False)
    op.create_table('room_access_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_access_logs_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_access_logs'))
    )
    op.create_index('ix_room_access_logs_created_at', 'room_access_logs', ['created_at'], unique=False)
    op.create_index('ix_room_access_logs_room_id', 'room_access_logs', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_room_access_logs_room_id', table_name='room_access_logs')
    op.drop_index('ix_room_access_logs_created_at', table_name='room_access_logs')
    op.drop_table('room_access_logs')
    op.drop_index('ix_security_events_severity', table_name='security_events')
    op.drop_index('ix_security_events_created_at', table_name='security_events')
    op.drop_table('security_events')
    op.drop_index('ix_rooms_room_code', table_name='rooms')
    op.drop_index('ix_rooms_last_activity_at', table_name='rooms')
    op.drop_index('ix_rooms_is_active', table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
